### ISSUE TITLE
Pike crash

### ISSUE THREAD

**Issue by TheDarkPreacher** [minecraftabnormals/Upgrade-Aquatic#10]
Testing in single player instance of the Devcraft pack with the new UA version (version Wave Three - Beta v1.04) and was simply travelling through the world when there was a sudden lag spike, then game crashed, producing this log: https://pastebin.com/Yz00HNHF

After the crash, loaded the world back up, continued on my way, and never saw a single pike.

**Comment by SmellyModder** [comment]
Your aren't running the correct forge version

**Comment by SmellyModder** [comment]
java.lang.NoClassDefFoundError: net/minecraft/world/server/ServerWorld Would only happen if you were running an older forge

**Comment by TheDarkPreacher** [comment]
![image](https://user-images.githubusercontent.com/15058826/62182734-57cd3300-b31d-11e9-9fda-097ae4a79f84.png)

Forge 28.0.23. Same as what EpicSquid included with the Twitch Export, and all I did was drop in the new version of UA. Should I bump Forge to a higher version like 28.0.27 to keep crashes like that from happening?

**Comment by SmellyModder** [comment]
Technically it should work fine on any 1.14.4 forge version

**Comment by SmellyModder** [comment]
But like I said, "java.lang.NoClassDefFoundError: net/minecraft/world/server/ServerWorld". ClassNotFoundException and NoClassDefFoundError both occur when class is not found at runtime, which would only happen if the forge version you're running doesn't have the proper package name for that class

**Comment by TheDarkPreacher** [comment]
¯\_(ツ)_/¯

**Comment by SmellyModder** [comment]
shrug is right lol

**Comment by TheDarkPreacher** [comment]
I dunno, man, I just work here.

**Comment by TheDarkPreacher** [comment]
New development: Upped Forge to 28.0.27, got this crash on load of world: https://pastebin.com/itJK1gKA
